[package]
name = "twitter-mute-sync"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]
edition = "2018"

[dependencies]
egg-mode = "0.12.0"
serde = "1.0.91"
serde_derive = "1.0.91"
toml = "0.5.1"
tokio-core = "0.1.17"
